// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTA_API.Data;

#nullable disable

namespace TTA_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016175620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TTA_API.Models.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookerUserId")
                        .HasColumnType("int");

                    b.Property<string>("TripType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookerUserId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("TTA_API.Models.AllocationTraveler", b =>
                {
                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AllocationTravelers");
                });

            modelBuilder.Entity("TTA_API.Models.Holiday", b =>
                {
                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HolidayDate");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("TTA_API.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("TTA_API.Models.PlanSelectedDay", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.HasKey("PlanId", "Day");

                    b.ToTable("PlanSelectedDays");
                });

            modelBuilder.Entity("TTA_API.Models.SystemSettings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingsId"));

                    b.Property<bool>("AllocateForCurrentMonth")
                        .HasColumnType("bit");

                    b.Property<string>("ArrivalLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TripPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("UserListViewEnabled")
                        .HasColumnType("bit");

                    b.HasKey("SettingsId");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            SettingsId = 1,
                            AllocateForCurrentMonth = true,
                            ArrivalLabel = "Arrival",
                            DepartureLabel = "Departure",
                            TripPrice = 240.00m,
                            UserListViewEnabled = true
                        });
                });

            modelBuilder.Entity("TTA_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("SendEmail")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alloc-admin@trip.com",
                            Name = "Allocation Admin",
                            Pin = "0000",
                            Role = 0,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 2,
                            Email = "sys-admin@trip.com",
                            Name = "System Admin",
                            Pin = "0000",
                            Role = 2,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 3,
                            Email = "gayathri@trip.com",
                            Name = "Gayathri",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 4,
                            Email = "gokul@trip.com",
                            Name = "Gokul",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 5,
                            Email = "kiruthika@trip.com",
                            Name = "Kiruthika",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 6,
                            Email = "narendran@trip.com",
                            Name = "Narendran",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 7,
                            Email = "navin@trip.com",
                            Name = "Navin",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 8,
                            Email = "sangeetha@trip.com",
                            Name = "Sangeetha",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 9,
                            Email = "sarath@trip.com",
                            Name = "Sarath",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        },
                        new
                        {
                            Id = 10,
                            Email = "shalini@trip.com",
                            Name = "Shalini",
                            Pin = "1001",
                            Role = 1,
                            SendEmail = true
                        });
                });

            modelBuilder.Entity("TTA_API.Models.Allocation", b =>
                {
                    b.HasOne("TTA_API.Models.User", "Booker")
                        .WithMany()
                        .HasForeignKey("BookerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booker");
                });

            modelBuilder.Entity("TTA_API.Models.AllocationTraveler", b =>
                {
                    b.HasOne("TTA_API.Models.Allocation", "Allocation")
                        .WithMany("Travelers")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTA_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Allocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TTA_API.Models.Plan", b =>
                {
                    b.HasOne("TTA_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TTA_API.Models.PlanSelectedDay", b =>
                {
                    b.HasOne("TTA_API.Models.Plan", "Plan")
                        .WithMany("SelectedDays")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TTA_API.Models.Allocation", b =>
                {
                    b.Navigation("Travelers");
                });

            modelBuilder.Entity("TTA_API.Models.Plan", b =>
                {
                    b.Navigation("SelectedDays");
                });
#pragma warning restore 612, 618
        }
    }
}
